config/routes.rb
Yumlicious::Application.routes.draw do
  get "sessions/new"

  resources :restaurants

  resources :reviews

  resources :users
  
  resources :sessions, :only => [:new, :create, :destroy]

  get "pages/home"

  get "pages/about"

  get "pages/contact"
  
  root :to => 'pages#home'
  
  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

end

app/views/layouts/_footer.html.erb
<footer>
	<div id="footer">
		<%= link_to 'About', about_path %> | 
		<%= link_to 'Contact', contact_path %> |
		<%= link_to 'Home', root_path %> | 
		
		<% if signed_in? %>
		<%= link_to "Sign out", signout_path, :method => :delete %>
		<% else %>
		<%= link_to "Sign in", signin_path %>
		<% end %>
	</div>
		
</footer>

app/views/layouts/_header.html.erb
<header>
	<div id="header">
		YUMLICIOUS
	</div>
</header>

app/views/layouts/_menu.html.erb
<div id="menu">
		<p>
		<% if signed_in? %>
		<%= link_to "Profile", current_user%><br/>
		<% end %>
		<%= link_to 'View highest rated restaurants in your area', '#'%><br/>
		<%= link_to 'View newest restaurants in your area', '#'%>
		</p>
</div>

app/views/layouts/_stylesheets.html.erb
<%= stylesheet_link_tag 'yumstyle', :media => 'screen' %>
<%= stylesheet_link_tag 'yumstyle', :media => 'print' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		
		<title>Yumlicious | <%= @title %></title>
		<%= csrf_meta_tag %>

		<%= stylesheet_link_tag "application" %>
		
	</head>
	
	<body>
		
		<%= render 'layouts/header'%>
		
		<section class ="round">
			<% flash.each do |key, value| %>
				<div class="flash <%= key %>"><%= value %> </div>
			<% end %>
			<!--<%= yield %>-->
		</section>
			

		
		<div id="container">
			<div id="inner">
			
			<%= render 'layouts/menu'%>
				
				<div id="content">
					<%= yield %>
				</div>
					
			</div>
			
		</div>
			
		<%= render 'layouts/footer'%>
			
	</body>
</html>